### ISSUE TITLE
getKittyIds

### ISSUE THREAD

**Issue by LeRoyJulian** [ricmoo/ethers-meow#9] opened 2017-12-08 13:10 UTC
I want to use the function getKittyIds to get the list of cats of given address, but I get an empty array. Can you help me to find why?

**Comment by ricmoo** [comment] 2017-12-08 22:36
This unfortunately will likely never work again.

It's been failing against many nodes for a while now, and even against Etherscan no longer works.

The problem is the call (while read-only) is computationally expensive, so as some point the node you are reading from refuses to respond to it.

There is no easy nor succinct solution, unfortunately. I am working on a service that will expose this as a web API, but for now you will either need to crawl the CryptoKitties web API or build your own local cache by querying each kitty on the blockchain for it's current owner.

**Comment by ricmoo** [comment] 2017-12-11 16:09
Closing. If you have further questions though, please feel free to re-open.

**Closed as completed by ricmoo** 2017-12-11 16:09 UTC
